# ND arrays
1. [форма массива](#form)
2. [изменение формы массива reshape](#change_form)
3. [транспонирование](#transpose)
4. [умножение матрицы](#multipl)
55. [задачки](#tasks)

In [1]:
import numpy as np

In [2]:
matrix = [[1, 2, 3], [4, 5, 6]]
matrix

[[1, 2, 3], [4, 5, 6]]

In [3]:
np_m = np.array(matrix)
np_m

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
np_m2 = np_m + 0.5
np_m2

array([[1.5, 2.5, 3.5],
       [4.5, 5.5, 6.5]])

In [5]:
np.append(np_m, 7)

array([1, 2, 3, 4, 5, 6, 7])

In [6]:
mat3d = np.array([np_m, np_m2])
mat3d

array([[[1. , 2. , 3. ],
        [4. , 5. , 6. ]],

       [[1.5, 2.5, 3.5],
        [4.5, 5.5, 6.5]]])

In [7]:
np.ones((3, 4, 5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [8]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
np.ones(3)

array([1., 1., 1.])

In [10]:
np.full((3, 9, 4), 7)

array([[[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]],

       [[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]],

       [[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]]])

# Форма массива
<a id="form"></a> 

In [19]:
# две матрицы, в каждой матрице по две строки и три столбца  2 * 2 * 3
# и если матрица еще больше. как ее считать?
mat3d = np.array([[[1., 4., 9.],
                   [16, 25, 36]],
                   
                   [[49, 64, 81],
                    [100, 121, 144]]])
mat3d

array([[[  1.,   4.,   9.],
        [ 16.,  25.,  36.]],

       [[ 49.,  64.,  81.],
        [100., 121., 144.]]])

In [20]:
len(mat3d) # количество матриц

2

что если надо узнать размерность строчки. И тд. для этого есть метод shape. идет от внешнего слоя  к внутреннему

In [21]:
mat3d.shape # размерность матрицы(количество матриц, количество строк, количество столбцов)

(2, 2, 3)

In [24]:
# просто все переменожить и получим количество элементов матрицы
c = 1
for i in list(mat3d.shape):
    c *= i
c

12

In [25]:
np_m, mat3d

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[[  1.,   4.,   9.],
         [ 16.,  25.,  36.]],
 
        [[ 49.,  64.,  81.],
         [100., 121., 144.]]]))

In [28]:
np_m.ndim # количество измерений

2

In [30]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

arr.ndim

2

In [31]:
arr.shape

(3, 3)

# Изменение формы массива reshape
<a id="change_form"></a>

хочу изменить форму массива. например была матрица(2 строки по 3 элемента. а я хочу три строки по два элемента)

In [33]:
np_m

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
np_m.reshape(3, 2) # изменение размерности матрицы(количество строк, количество столбцов)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [35]:
np_m.reshape(6, 1) # изменение размерности матрицы(количество строк, количество столбцов)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [36]:
np_m.reshape(6) # одномерный массив

array([1, 2, 3, 4, 5, 6])

In [39]:
np_m.reshape(2,3,1) #

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [40]:
np_m # исходная матрица. не менялась. так как я не присвоил новую переменную

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
np_m = np_m.reshape(3, 2) # присвоил новую переменную
np_m

array([[1, 2],
       [3, 4],
       [5, 6]])

In [42]:
reshaped = np_m.reshape(2, 3)
reshaped

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
reshaped[0]= 0 # изменение элементов матрицы. первая строка равна 0
reshaped

array([[0, 0, 0],
       [4, 5, 6]])

In [44]:
np_m # исходная матрица изменилась. так как я не создал новую переменную

array([[0, 0],
       [0, 4],
       [5, 6]])

In [45]:
arr = np.arange(8)
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [48]:
arr = arr.reshape(8) # одномерный массив
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [49]:
arr.reshape(1, 1, 1, 1, 1, 1, 2, 2, 2) # 

array([[[[[[[[[0, 1],
              [2, 3]],

             [[4, 5],
              [6, 7]]]]]]]]])

# транспонирование (переворот)
<a id='transpose'></a>

In [69]:
np_m = np.arange(8).reshape(2, 4)
np_m

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [70]:
np_m.transpose() # транспонирование матрицы. типа переворачивание матрицы

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

In [71]:
np_m.T # тоже самое что и np_m.transpose()

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

In [75]:
m = np.arange(4)
m

array([0, 1, 2, 3])

In [76]:
m.T # транспонирование одномерного массива не работает

array([0, 1, 2, 3])

# Умножение матрицы
<a id='multipl'></a>

In [ ]:
# умножение матриц. количество столбцов первой матрицы должно быть равно количеству строк второй матрицы. 
# если матрица 2 на 3 то вторая матрица должна быть 3 на 2


In [80]:
# np_m @ np_m # умножение матриц не получился так как количество столбцов первой матрицы не равно количеству строк второй матрицы
np_m @ np_m.T # умножение матриц. новая форма получается 2 на 2. так как берется количество строк первой матрицы и количество столбцов второй матрицы

array([[ 14,  38],
       [ 38, 126]])

# Задачки
<a id="tasks"></a>

In [60]:
import numpy as np

def solution(arr):
    """ 
    преобразует матрицу в одномерный массив
    """

    # return arr.flatten()  # Преобразует матрицу в одномерный массив и возвращает его копию
    return arr.reshape(-1)  # Преобразует матрицу в одномерный массив, возвращая представление (view) массива, если это возможно

arr = np.random.rand(4, 4, 4)
a = solution(arr)

In [59]:
a

array([7.95324986e-01, 2.20355079e-01, 8.65348062e-01, 5.52384730e-01,
       8.57457313e-01, 7.78057451e-01, 9.45329160e-01, 9.21227260e-01,
       9.26204239e-01, 1.06359056e-01, 8.88511981e-01, 6.47474817e-01,
       6.56314626e-01, 6.46357277e-01, 7.42368972e-01, 4.07704207e-01,
       1.93443507e-01, 6.36609210e-04, 5.64177687e-01, 8.57367990e-01,
       9.42986415e-01, 9.49403102e-02, 4.48904590e-02, 6.75271385e-01,
       2.26779181e-01, 2.86098569e-01, 3.10918421e-01, 4.40709290e-01,
       5.22787243e-01, 5.86226354e-02, 3.22268858e-01, 4.04243195e-01,
       2.71505785e-01, 4.29951722e-01, 4.66814476e-01, 8.41549142e-01,
       4.39185940e-02, 1.02664758e-01, 9.50380326e-01, 7.54103492e-01,
       3.66451958e-01, 5.50003948e-01, 9.63666556e-01, 8.01816911e-01,
       3.16634060e-02, 2.72070512e-01, 5.45086006e-01, 1.02587478e-01,
       5.89251006e-01, 3.10138769e-01, 4.52521328e-01, 4.44420123e-01,
       8.68808243e-01, 9.36623849e-01, 7.22788639e-01, 6.14631503e-02,
      

In [65]:
import numpy as np

# np.random.rand(2, 2, 2, 2)
def solution(arr):
    """ 
    преобразует матрицу в одномерный массив, если количество измерений больше или равно 2
    в противно случае преобразует в матрицу (2, 2, 2, 2)
    """
    if arr.ndim >= 2:
        return arr.reshape(-1)
    else:
        return arr.reshape(2, 2, 2, 2)



In [89]:
arr = np.arange(16).reshape(4, 2, 2)
# arr
arr.T * 2


array([[[ 0,  8, 16, 24],
        [ 4, 12, 20, 28]],

       [[ 2, 10, 18, 26],
        [ 6, 14, 22, 30]]])

In [ ]:
def solution(arr):
    """ 
    транспонирование и умножение каждого элемента на 2
    """
    return arr.T * 2