# masks_index_slices
1. [Masks](#masks)
2. [Slicing](#slicing)
3. [Задачки](#tasks)

# Маски
<a id="masks"></a>

In [1]:
import numpy as np
fives = np.full((2, 3, 4), 5)
fives


array([[[5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5]],

       [[5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5]]])

In [2]:
arr1 = np.array([1, 4, 9])
arr2 = np.array([9, 4, 1])
arr1, arr2

(array([1, 4, 9]), array([9, 4, 1]))

In [3]:
arr1 > 5 # сравнивает элементы массива с числом 5

array([False, False,  True])

In [4]:
arr2 >= 4

array([ True,  True, False])

In [5]:
m = np.array([10, 10, 10])
m > arr1

array([ True,  True,  True])

In [6]:
arr1 >= arr2

array([False,  True,  True])

In [7]:
arr1[[False, True, True]] # возвращает элементы массива, соответствующие True, в данном случае 4 и 9

array([4, 9])

# Slicing
<a id="slicecing"></a>


In [10]:
lst = [1,2,3,4,5,6,7,8,9,10]
lst

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [13]:
lst[2:5] # срез списка (левая граница включается, правая нет)

[3, 4, 5]

In [23]:
arr1 = np.arange(9)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [24]:
arr1[2] # правлиа индексации такие же как и у списков в Python

2

In [28]:
arr_slice = arr1[2:7]
arr_slice

array([2, 3, 0, 5, 6])

In [27]:
arr_slice[2] = 0
arr_slice

array([2, 3, 0, 5, 6])

In [29]:
arr1 # изменение среза изменяет исходный массив

array([0, 1, 2, 3, 0, 5, 6, 7, 8])

In [30]:
arr_slice_copy = arr1[2:7].copy()
arr_slice_copy

array([2, 3, 0, 5, 6])

In [31]:
arr_slice_copy[2] = 10

In [32]:
arr_slice_copy

array([ 2,  3, 10,  5,  6])

In [33]:
arr1 # изменение копии среза не влияет на исходный массив!!!! использовать copy() для создания копии среза

array([0, 1, 2, 3, 0, 5, 6, 7, 8])

In [35]:
arr = np.arange(8).reshape(2, 4)
arr

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [38]:
arr[0] # возвращает первую строку массива

array([0, 1, 2, 3])

In [39]:
arr[0, 2] # возвращает элемент массива, находящийся на пересечении 0 строки и 2 столбца

2

In [40]:
arr[-1, -1] # возвращает элемент массива, находящийся на пересечении последней строки и последнего столбца

7

In [66]:
mat3d = np.arange(12).reshape(2, 2, 3) # создание трехмерного массива(матрицы)
mat3d

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [45]:
# как например обратиться к 5. 5 находится в первой матрице, во второй строке в последнем столбце. 
# значит: обращаюсь к первой матрице 0, второй строке 1 и последнему столбцу -1 или 2, так как индексация начинается с 0 [0, 1, -1]

mat3d[0, 1, -1] 

5

In [48]:
# how to take a third column from 3d matrix 
# так как нас не интересует какая то конкреттная матрица, то ставлю двоеточие, чтобы обратиться ко всем матрицам. И так как не 
# интересует стройка то тоже ставлю двоеточие, а вот столбец интересует, поэтому указываю его индекс [:, :, 1]
mat3d[:, :, 1] # возвращает второй столбец из всех матриц

array([[ 1,  4],
       [ 7, 10]])

In [49]:
mat3d[:, :, 1:] # возвращает все столбцы начиная со второго столбца

array([[[ 1,  2],
        [ 4,  5]],

       [[ 7,  8],
        [10, 11]]])

In [50]:
mat3d[1, :, 1:]

array([[ 7,  8],
       [10, 11]])

In [51]:
# первые строчкии
mat3d[:, 0, :] # возвращает первые строки из всех матриц

array([[0, 1, 2],
       [6, 7, 8]])

In [61]:
mat3d[:,0] = -4 # присваивание значений всем элементам первой строки всех матриц
mat3d

array([[[-4, -4, -4],
        [ 3,  4,  5]],

       [[-4, -4, -4],
        [ 9, 10, 11]]])

In [62]:
msclice = mat3d[1, 1] # последняя строчка последней матрицы
msclice

array([ 9, 10, 11])

In [63]:
msclice[:] = -4
msclice

array([-4, -4, -4])

In [65]:
mat3d # изменение среза изменяет исходный массив. опять что бы этого избежать нужно использовать copy() для создания копии среза

array([[[-4, -4, -4],
        [ 3,  4,  5]],

       [[-4, -4, -4],
        [-4, -4, -4]]])

In [67]:
mat3d = np.arange(12).reshape(2, 2, 3) # создание трехмерного массива(матрицы)
mat3d

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [68]:
msclice = mat3d[1, 1].copy() # последняя строчка последней матрицы
msclice

array([ 9, 10, 11])

In [70]:
msclice[:] = 99
msclice

array([99, 99, 99])

In [71]:
mat3d

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

# Задачки
<a id="tasks"></a>

In [52]:
mat3d = np.arange(12).reshape(2, 2, 3) # создание трехмерного массива(матрицы)
mat3d


array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [57]:
def solution(arr):
    """ 
    программa, выдающую последний элемент последней строки последней матрицы этого массива.
    """
    return arr[-1, -1, -1]
mat3d[-1, -1, -1]

11

In [72]:
arr = np.arange(8).reshape(2, 4)
arr

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [76]:
# Программа принимает на вход матрицу 2*4. Напишите программу, возвращающую указанную подматрицу.
arr[:, 1:3]

array([[1, 2],
       [5, 6]])

In [80]:
# На вход подается произвольная матрица. Выполните поэлементное сравнение (==) двух столбцов (первого и последнего):

arr[:,0] == arr[:,-1]

array([False, False])

In [81]:
arr1 = np.arange(16).reshape(4, 4)

arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [87]:
# Программа принимает на вход матрицу 4*4. Напишите программу, возвращающую указанную подматрицу.

def solution(arr):
    return arr[1:3, 1:3]

In [88]:
#На вход программе подаётся матрица 3*3. Транспонируйте её, а затем допишите код так,
#  чтобы он возвращал матрицу 2*2, которая находится в правом верхнем углу получившейся матрицы.
arr3 = np.arange(9).reshape(3,3)
arr3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [101]:
arr3[0:2, 1:]

array([[1, 2],
       [4, 5]])

In [102]:
def solution(arr):
    """
    Эта функция транспонирует массив и возвращает подмассив.
    который находится в правом верхнем углу получившейся матрицы.

    Args:
        arr (np.ndarray): Входной массив.

    Returns:
        np.ndarray: Подмассив транспонированного массива.

    Raises:
        None
    """

    new_arr = arr.T
    return new_arr[0:2, 1:]


solution(arr3)

array([[3, 6],
       [4, 7]])

In [103]:
arr3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [108]:
# Подается массив. Допишите код так, чтобы он возвращал новый массив, содержащий все значения исходного, превышающие  10. 
def solution(arr):
    new_arr = arr.copy()
    return new_arr[new_arr > 10]


In [109]:
# след матрицы(сумма всех элементов матрицы слева по диагонали слева вниз. типа из левого верхнего угла в правый нижний)
arr4 = np.arange(16).reshape(4,4)


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [110]:
def solution(arr):
    """
    Эта функция возвращает след матрицы.

    Args:
        arr (np.ndarray): Входной массив.

    Returns:
        int: След матрицы.

    Raises:
        None
    """

    return np.trace(arr)

solution(arr4)

30

In [114]:
def solution(arr):
    """
    Эта функция возвращает след матрицы.
    без встроенной функции np.trace()
    """
    trace = 0
    for i in range(len(arr)):
        trace += arr[i][i]
    print(trace)
    return sum(arr[i][i] for i in range(len(arr)))

solution(arr4)

30


30