#Something
1. [fancy](#fancy-indexing)
2. [advanced masks](#advanced-masks)
3. [Задачки](#tasks)

In [88]:
import numpy as np

# Fancy indexing


In [89]:
m = np.arange(12).reshape(3, 4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [90]:
# что если я хочу взять первую и последнюю строки? 
m[[True, False, True]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [91]:
# fancy indexing
m[[0, 2]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [92]:
m[[0, 2],1:] # первая и последняя строки, колонки с 1 по последнюю

array([[ 1,  2,  3],
       [ 9, 10, 11]])

In [93]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [94]:
m[[0, 2, 2],[1,0, 3]] # 

array([ 1,  8, 11])

когда мы применяем маску мы создаем новый объект



In [95]:
m = np.arange(8)
m

array([0, 1, 2, 3, 4, 5, 6, 7])

In [96]:
# zeroes and ones часто используются для создания масок
mask = np.zeros(8, dtype=bool)
mask

array([False, False, False, False, False, False, False, False])

In [97]:
mask[1] = 1
mask[-1] = 1
mask

array([False,  True, False, False, False, False, False,  True])

In [98]:
# создаю массив x из m, но только из элементов, которые соответствуют маске и если потом как то менять массив x, то массив m не изменится
x = m[mask]
x

array([1, 7])

# advanced masks

In [99]:
users = np.array(['alex', 'gini', 'josh', 'alex'])
users

array(['alex', 'gini', 'josh', 'alex'], dtype='<U4')

In [100]:
scores = np.array([[1,2,3],
                   [0,6,8],
                   [0,-3,6],
                   [6,6,6]])
scores

array([[ 1,  2,  3],
       [ 0,  6,  8],
       [ 0, -3,  6],
       [ 6,  6,  6]])

In [101]:
scores[users == 'alex'] # выведет только строки, где пользователь alex

array([[1, 2, 3],
       [6, 6, 6]])

In [102]:
scores[users == 'alex', 1:] # выведет только строки, где пользователь alex и колонки с 1 по последнюю

array([[2, 3],
       [6, 6]])

In [103]:
scores[scores % 2 == 0] # выведет только четные числа

array([2, 0, 6, 8, 0, 6, 6, 6, 6])

In [104]:
scores[users == 'alex', 1:] # выведет только строки, где пользователь alex и колонки с 1 по последнюю

array([[2, 3],
       [6, 6]])

In [105]:
users, scores

(array(['alex', 'gini', 'josh', 'alex'], dtype='<U4'),
 array([[ 1,  2,  3],
        [ 0,  6,  8],
        [ 0, -3,  6],
        [ 6,  6,  6]]))

In [106]:
# создаю маску где пользователь alex
mask = users == 'alex'
mask

array([ True, False, False,  True])

In [107]:
mask1 = users != 'alex'
mask1

array([False,  True,  True, False])

In [108]:
~mask # инвертирую маску на оборот

array([False,  True,  True, False])

In [109]:
scores[~mask] # выведет только строки, где пользователь не alex

array([[ 0,  6,  8],
       [ 0, -3,  6]])

In [110]:
scores[mask] # выведет только строки, где пользователь alex

array([[1, 2, 3],
       [6, 6, 6]])

In [111]:
# если нужно сделать маску для нескольких пользователей, то or не будет работать и нужно использовать np.logical_or или |
mask2 = np.logical_or(users == 'alex', users == 'gini')
mask3 = (users == 'alex') | (users == 'gini')
mask2, mask3


(array([ True,  True, False,  True]), array([ True,  True, False,  True]))

In [112]:
scores[mask2]

array([[1, 2, 3],
       [0, 6, 8],
       [6, 6, 6]])

In [113]:
m1 = scores % 2 == 0
m2 = scores % 3 != 0
# теперь если нужно сделтаь логической операцию and, то нужно использовать np.logical_and или &
m3 = np.logical_and(m1, m2)
m4 = m1 & m2
m1, m2

(array([[False,  True, False],
        [ True,  True,  True],
        [ True, False,  True],
        [ True,  True,  True]]),
 array([[ True,  True, False],
        [False, False,  True],
        [False, False, False],
        [False, False, False]]))

In [114]:
scores[m3]

array([2, 8])

In [115]:
scores[m1 & ~m2]

array([0, 6, 0, 6, 6, 6, 6])

# Tasks

In [116]:
import numpy as np

arr = np.arange(25).reshape(5, 5)



def solution(a,b,arr):
    """ 
    функция возврщает два столбца из массива arr
    a,b - индексы столбцов
    """
    return arr[:,[a,b]]

In [117]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [118]:
a = 2
b = 3
arr[:,[a,b]]

array([[ 2,  3],
       [ 7,  8],
       [12, 13],
       [17, 18],
       [22, 23]])

In [119]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [120]:
x = -7
-x

7

In [121]:
#Программа получает на вход число n и массив натуральных чисел длины n. Допишите код так,
#  чтобы он возвращал массив, содержащий все элементы исходного массива, которые делятся на 3 и утроенный модуль которых больше 40.
arr = np.arange(33)

def solution(arr):
    # Находим утроенный модуль для каждого элемента массива
    triple_abs = np.abs(arr) * 3
    
    # Первое условие: утроенный модуль больше 40
    m1 = triple_abs > 40
    
    # Второе условие: элемент делится на 3
    m2 = arr % 3 == 0
    
    # Комбинируем два условия с помощью np.logical_and
    mask = np.logical_and(m1, m2)
    
    # Возвращаем элементы массива, удовлетворяющие обоим условиям
    return arr[mask]

solution(arr)

array([15, 18, 21, 24, 27, 30])

In [122]:
# Программа получает на вход массив натуральных чисел длины n. Допишите код так, чтобы он возвращал массив, содержащий все элементы исходного массива, 
# которые дают остаток 2 при делении на 5 или те, куб которых меньше 100.

def solution(arr):

    return arr[(arr % 5 == 2) | (arr ** 3 < 100)]


In [123]:
import numpy as np

arr = np.arange(16).reshape(4, 4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [124]:
arr[[True, False, True, True], 1:3] # выведет строки 0, 2, 3 и колонки с 1 по 3

array([[ 1,  2],
       [ 9, 10],
       [13, 14]])

In [125]:
arr[:,:3] # выведет все строки и колонки с 0 по 3

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

In [126]:
arr[3,2] # выведет элемент 3 строки и 2 колонки, индексы начинаются с 0, поэтому число 14

14

In [127]:
arr[[1,2], [3,3]]

array([ 7, 11])

In [128]:
# На вход подается двумерная матрица (4, 4). Преобразуйте ее в одномерный массив.
arr = np.arange(16).reshape(4, 4)
arr.reshape(16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [129]:
#Программа принимает на  вход массив. Оставьте все значения данного массива, большие либо равные 4, либо делящиеся на 3 без остатка.
def solution(arr):
    return arr[(arr >= 4) | (arr % 3 == 0)] 

In [130]:
# Программе подается на вход массив. Транспонируйте его, поменяв тип данных на int.
arr.T.astype(int)

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

In [131]:
# Подаются два массив 4*4. Сложите их, а затем вырежьте "центральную" подматрицу данной матрицы
arr1 = np.arange(16).reshape(4, 4)
arr2 = np.arange(16).reshape(4, 4)
arr3 = arr1 + arr2
arr3, arr3[1:3, 1:3]

(array([[ 0,  2,  4,  6],
        [ 8, 10, 12, 14],
        [16, 18, 20, 22],
        [24, 26, 28, 30]]),
 array([[10, 12],
        [18, 20]]))

In [132]:
arr3[1:3, 1:3]

array([[10, 12],
       [18, 20]])

In [133]:
# Подается массив формы (4, 4).
# Верните массив состоящий из:
#Первого элемента первой строки
#Второго элемента второй строки
#Третьего элемента четвертой строки
#Первого элемента четвертой строки
arr = np.arange(16).reshape(4, 4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [134]:
def solution(arr):
    return np.array([arr[0,0], arr[1,1], arr[3,2], arr[3,0]])
solution(arr)

array([ 0,  5, 14, 12])

In [135]:
def solution(arr):
    return arr[[0,1,3,3], [0,1,2,0]]
solution(arr)

array([ 0,  5, 14, 12])

In [136]:
#На вход подается матрица.
#Поменяйте все элементы данного массива в диапазоне от 3 до 7 (включительно) на их квадрат. 
#Все отрицательные элементы замените их модулем. Получившуюся матрицу транспонируйте.

def solution(arr):  
    #  выбирает только те элементы массива arr, которые соответствуют условию с помощью булевой индексации и возводит их в квадрат
    arr[(arr >= 3) & (arr <= 7)] = arr[(arr >= 3) & (arr <= 7)] ** 2
    arr[arr < 0] = np.abs(arr[arr < 0])
    return arr.T
