1. [functions 1](#functions-1)
2. [functions 2(mean,floor, ceil etc)](#functions-2)
5. [tasks](#tasks-1)

# functions 1

In [1]:
import numpy as np

In [2]:
scores = np.array([[1,2,3],
                   [0,6,8],
                   [0,-3,6],
                   [6,6,6]])
scores

array([[ 1,  2,  3],
       [ 0,  6,  8],
       [ 0, -3,  6],
       [ 6,  6,  6]])

In [5]:
# посчитать корень. 
scores ** (1/2), np.sqrt(scores)

/tmp/ipykernel_5348/2983284240.py:2: RuntimeWarning: invalid value encountered in power
  scores ** (1/2), np.sqrt(scores)
/tmp/ipykernel_5348/2983284240.py:2: RuntimeWarning: invalid value encountered in sqrt
  scores ** (1/2), np.sqrt(scores)


(array([[1.        , 1.41421356, 1.73205081],
        [0.        , 2.44948974, 2.82842712],
        [0.        ,        nan, 2.44948974],
        [2.44948974, 2.44948974, 2.44948974]]),
 array([[1.        , 1.41421356, 1.73205081],
        [0.        , 2.44948974, 2.82842712],
        [0.        ,        nan, 2.44948974],
        [2.44948974, 2.44948974, 2.44948974]]))

In [7]:
# abs что делает? - вычисляет модуль. Модуль числа - это число без знака. тоесть если число с минусом, то модуль это число без минуса.
np.abs(scores), abs(scores), scores

(array([[1, 2, 3],
        [0, 6, 8],
        [0, 3, 6],
        [6, 6, 6]]),
 array([[1, 2, 3],
        [0, 6, 8],
        [0, 3, 6],
        [6, 6, 6]]),
 array([[ 1,  2,  3],
        [ 0,  6,  8],
        [ 0, -3,  6],
        [ 6,  6,  6]]))

In [16]:
# сумма всех элементов/сумма всех модулей элементов. некоторые функции работают как функции класса
np.sum(scores), np.sum(np.abs(scores)), scores.sum()

(41, 47, 41)

In [12]:
c = 0
for i in scores:
    for j in i:
        c += j

c

41

In [18]:
# максимальное значение, минимальное значение, среднее значение, стандартное отклонение, дисперсия
scores.max(), scores.min(), scores.mean(), scores.std(), scores.var()

(8, -3, 3.4166666666666665, 3.2521360501813095, 10.57638888888889)

In [21]:
# индекс максимального значения/индекс минимального значения
np.argmax(scores), np.argmin(scores)

(5, 7)

In [30]:
bm = np.array([1,0,1,0,1,1,], dtype=bool)
bm

array([ True, False,  True, False,  True,  True])

In [32]:
bm.sum() # вернет количество True в массиве

4

# functions 2

In [60]:
bm.mean(), scores.mean() # среднее значение... сумма всех элементов деленное на количество элементов

(0.6666666666666666, 3.4166666666666665)

In [63]:
# медиана - это значение, которое делит выборку на две равные части. 
# Если в выборке четное количество элементов, то медиана это среднее значение двух средних значений. 
# А если нечетное, то это среднее значение.
np.median(scores), scores

(4.5,
 array([[ 1,  2,  3],
        [ 0,  6,  8],
        [ 0, -3,  6],
        [ 6,  6,  6]]))

In [76]:
np.sort(np.append(scores.reshape(12), 7)) # сортировка по строкам

array([-3,  0,  0,  1,  2,  3,  6,  6,  6,  6,  6,  7,  8])

In [77]:
scores

array([[ 1,  2,  3],
       [ 0,  6,  8],
       [ 0, -3,  6],
       [ 6,  6,  6]])

In [79]:
# медиана - это значение, которое делит выборку на две равные части. 
# Если в выборке четное количество элементов, то медиана - это среднее значение двух средних элементов
np.median(scores) 

4.5

In [80]:
np.median(np.sort(np.append(scores.reshape(12), 7))) # сортировка по строкам  и медиана

6.0

In [84]:
arr = np.array([1.1, 1.9, 2.5, 9, 2.51])
arr

array([1.1 , 1.9 , 2.5 , 9.  , 2.51])

In [85]:
np.round(arr) # округление до целого куда ближе к ближайшему целому. если 2.5, то к 2. если 2.6, то к 3

array([1., 2., 2., 9., 3.])

In [87]:
# а что если надо округлить в меньшую сторону?
# astype(int) - приведение к целому числу и отбрасывание дробной части
# np.floor - округление в меньшую сторону
# np.ceil - округление в большую сторону
arr.astype(int), np.floor(arr), np.ceil(arr)

(array([1, 1, 2, 9, 2]),
 array([1., 1., 2., 9., 2.]),
 array([2., 2., 3., 9., 3.]))

In [88]:
x = 2.41
np.floor(x), np.ceil(x), np.round(x)

(2.0, 3.0, 2.0)

In [89]:
scores

array([[ 1,  2,  3],
       [ 0,  6,  8],
       [ 0, -3,  6],
       [ 6,  6,  6]])

In [93]:
# сумма по строкам, сумма по столбцам. axis=0 - столбцы, axis=1 - строки, axis=None - все
scores.max(axis=0), scores.max(axis=1), scores.max(axis=None)

(array([6, 6, 8]), array([3, 8, 6, 6]), 8)

# Tasks 1


Программе подается массив 5х5 вещественных чисел. Допишите код так, чтобы программа возвращала сумму квадратов тех элементов массива, которые находятся в нечетных(при нумерации столбцов начинающейся с единицы) столбцах и чьи значения  не превышают 15

In [35]:
arr = np.arange(10, 35).reshape(5,5)
arr

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [40]:
arr[:,1:-1:2] > 15

array([[False, False],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True]])

In [49]:
new_arr = arr[:, ::2].copy() # копируем массив и беру только четные столбцы
m = new_arr < 15 # беру только те значения которые больше 15
new_arr = new_arr[m] ** 2 # возвожу в квадрат все значения которые больше 15
new_arr.sum() # суммирую все значения в массиве

440

In [50]:
import numpy as np

def solution(arr):
    new_arr = arr[:, ::2].copy() # копируем массив и беру только четные столбцы
    m = new_arr < 15 # беру только те значения которые больше 15
    new_arr = new_arr[m] ** 2 # возвожу в квадрат все значения которые больше 15
    summa = new_arr.sum() # суммирую все значения в массиве
    return summa

Программа получает на вход массив. Допишите код так, чтобы она возвращала номер максимального по модулю значения массива. Нумерация начинается с нуля.

In [52]:
# массив рандомный с отрицательными и положительными значениями
arr = np.random.randint(-10, 10, size=(5,5))
arr

array([[  8,   8,   2,   3,  -8],
       [  6,   1,  -9, -10,   2],
       [ -2,   8,   4,   5,   3],
       [ -8,   0,   8,   3, -10],
       [  5,  -5,  -4,  -7,  -7]])

In [56]:
np.argmax(np.abs(arr))

(8,)

In [57]:
s = arr.argmax()
s

0

На вход подается массив произвольной формы. Умножьте его значения на 4.3, округлите в большую сторону, умножьте на 3.7, а затем округлите в меньшую сторону.

In [96]:
arr = np.array([1.1, 1.9, 2.5, 9, 2.51])
arr 

array([1.1 , 1.9 , 2.5 , 9.  , 2.51])

In [98]:
def solution(arr):
    arr = arr * 4.3
    arr = np.ceil(arr)
    arr = arr * 3.7
    arr = np.floor(arr)
    
    # arr =np.floor(np.ceil(arr * 4.3) * 3.7)
    return arr 

solution(arr)

array([ 18.,  33.,  40., 144.,  40.])

На вход подается массив произвольной формы.

Если медиана массива больше среднего арифметического, округлите его значения в меньшую сторону.

Если медиана равна среднему, округлите согласно правилам арифметического округления
Если среднее больше медианы, округлите значения в большую сторону.

In [103]:
scores
scores.mean(), np.median(scores)

(3.4166666666666665, 3.2521360501813095, 4.5)

In [104]:
x = 4.5
np.floor(x), np.ceil(x), np.round(x)

(4.0, 5.0, 4.0)

In [ ]:
def solution(arr):
    ''' 
    Функция принимает на вход двумерный массив arr.
    Если медиана массива больше среднего значения массива, то возвращает округленный в меньшую сторону массив.
    Если медиана массива равна среднему значению массива, то возвращает округленный до целого массив.
    Если медиана массива меньше среднего значения массива, то возвращает округленный в большую сторону массив.
    '''
    if np.median(arr) > arr.mean():
        return np.floor(arr)
    elif np.median(arr) == arr.mean():
        return np.round(arr)
    else:
        return np.ceil(arr)