1. [any all](#any-all)
2. [isnan](#isnan-)
3. [sort and out](#sort-out)
4. [tasks](#tasks-)

In [1]:
import numpy as np

# any all

In [7]:
np_m = np.ones(4)
np_m[0] = 0

any возвращает True если хотя бы один элемент True или не нулевой

In [8]:
np_m.any()

True

In [9]:
np_m = np.zeros(4)
np_m

array([0., 0., 0., 0.])

In [6]:
np_m.any()

False

In [10]:
np_m[0] = 1
np_m.any()

True

all вернет True если все не нулевые или True

In [12]:
np_m.all(), np_m

(False, array([1., 0., 0., 0.]))

# Unique

In [14]:
np_m = np.ones(4)
np_m[0] = 0
np_m

array([0., 1., 1., 1.])

In [17]:
users = np.array(["gini", "alex", "lev", "lev", "gini"])
users, np.unique(users) # unique values in array

(array(['gini', 'alex', 'lev', 'lev', 'gini'], dtype='<U4'),
 array(['alex', 'gini', 'lev'], dtype='<U4'))

# isnan .

In [18]:
np.nan # nan может быть в массиве

nan

In [19]:
np.sqrt(np.array([-1]))

/tmp/ipykernel_19567/2308575511.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(np.array([-1]))


array([nan])

In [21]:
np_m = np.array([1, 2, 3, np.nan, 4])
np_m

array([ 1.,  2.,  3., nan,  4.])

In [22]:
np.isnan(np_m) # проверка на nan в массиве. вернет True там где nan

array([False, False, False,  True, False])

In [23]:
np_m[~np.isnan(np_m)] # ~ - инверсия. Вернет все значения кроме nan

array([1., 2., 3., 4.])

# sort out

In [27]:
# рандомный массив
np_m = np.random.rand(10)
np_m

array([0.02947669, 0.95378033, 0.07602109, 0.61261502, 0.62034631,
       0.28960539, 0.19266257, 0.42652768, 0.06943154, 0.28815408])

In [28]:
np_m.sort() # изменит массив и отсортирует его
np_m

array([0.02947669, 0.06943154, 0.07602109, 0.19266257, 0.28815408,
       0.28960539, 0.42652768, 0.61261502, 0.62034631, 0.95378033])

In [34]:
# Создание случайной матрицы размером 2x5 с элементами в диапазоне от -5 до 14
np_m = np.random.randint(-5, 15, size=(2, 5))
np_m

array([[-4, 12,  9,  3, 13],
       [ 2, -1, -3,  8, 11]])

In [35]:
np_m.sort(axis=0) # сортировка по столбцам
np_m

array([[-4, -1, -3,  3, 11],
       [ 2, 12,  9,  8, 13]])

In [36]:
np_m.sort(axis=1) # сортировка по строкам
np_m

array([[-4, -3, -1,  3, 11],
       [ 2,  8,  9, 12, 13]])

In [41]:
m1 = np.array([1, -2, 3])
m1

array([ 1, -2,  3])

In [39]:
np.abs(m1) # модуль чисел исходный массив не изменится

array([1, 2, 3])

In [43]:
np.abs(m1,out=m1) # модуль чисел исходный массив меняеся

array([1, 2, 3])

In [44]:
m1

array([1, 2, 3])

In [45]:
m2 = np.arange(7)
m2

array([0, 1, 2, 3, 4, 5, 6])

# tasks .

На вход подается одномерный массив длины 16. Поменяйте его форму на (4, 4), а затем проведите сортировку по строкам.



In [52]:
arr = np.random.randint(-5, 55, 16)
arr

array([ 0, 35, 42, 11, 42, 16, 53, 37, 33, 43, 11, 53, 42,  8,  5, 24])

In [53]:
def solution(arr):

    arr = arr.reshape(4, 4)
    arr.sort(axis=1)
    return arr

arr = solution(arr)
arr

array([[ 0, 11, 35, 42],
       [16, 37, 42, 53],
       [11, 33, 43, 53],
       [ 5,  8, 24, 42]])

На вход подается массив произвольной формы.

Если в нем нет нулей, верните массив обратных значений

Если в нем есть нули, то замените их единицами и верните массив обратных значений.

In [59]:
arr = np.random.randint(-5, 5, 16)
arr = np.array([ 4, -3, -4,  1, -4,  0,  0, -2, -4,  2, -1,  2, -3, -3, -5, -2])

In [66]:
def solution(arr):
    arr[arr == 0] = 1

    return 1 / arr

arr = solution(arr)
arr

array([ 0.25      , -0.33333333, -0.25      ,  1.        , -0.25      ,
        1.        ,  1.        , -0.5       , -0.25      ,  0.5       ,
       -1.        ,  0.5       , -0.33333333, -0.33333333, -0.2       ,
       -0.5       ])

На вход подается массив. Верните массив его уникальных значений.



In [68]:
arr = np.random.randint(-5, 5, 16)
arr

array([-2, -3, -2, -5, -5,  0, -5, -4,  3, -4, -1, -1,  1, -5, -5,  0])

In [70]:
def solution(arr):
    return np.unique(arr)

arr = solution(arr)
arr

array([-5, -4, -3, -2, -1,  0,  1,  3])