1. [бинарные функции](#binary-functions)
2. [where функция](#where-function)
3. [save to file](#save-to-file)
4. [tasks](#tasks-)

In [ ]:
# бинарные функции это функции которые принимают два аргумента

# binary functions

In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, -7, 9])
b = np.array([1, -4, 5, 6])
a, b

(array([ 1,  2, -7,  9]), array([ 1, -4,  5,  6]))

In [5]:
# что если надо найти максимальный элемент из двух массивов
max(a.max(), b.max()) # это неудобно. я исполую max обычный питоновский

9

In [6]:
np.maximum(a, b) # это бинарная функция. она принимает два массива и возвращает массив, где каждый элемент это максимальный элемент из двух массивов

array([1, 2, 5, 9])

In [7]:
np.minimum(a, b) # аналогично для минимального

array([ 1, -4, -7,  6])

In [8]:
a, b

(array([ 1,  2, -7,  9]), array([ 1, -4,  5,  6]))

In [10]:
a = np.array([1,4,5])
b = np.array([3,7,5])

In [12]:
a == b # возвращает массив булевых значений

array([False, False,  True])

In [15]:
(a == b).all(),   np.array_equal(a, b) # проверяет равны ли массивы

(False, False)

# WHERE function

In [24]:
a = np.array([1, 2, -7, 9])
b = np.array([1, -4, 5, 6])
a, b

(array([ 1,  2, -7,  9]), array([ 1, -4,  5,  6]))

In [20]:
# что если нужно замеить числа которые меньше 0 например. можно использоать маску, но это неудобно. лучше исопльзовать WHERE
a[a <= 2] = 0
a

array([0, 0, 0, 9])

In [23]:
 # первый аргумент это условие, второй аргумент это значение если условие выполняется, третий аргумент это значение если условие не выполняется
np.where(a <= 2, 0, a)

array([0, 0, 0, 9])

In [38]:
a = np.array([1, 2, -7, 9])
b = np.array([1, -4, 5, 6])
a, b

(array([ 1,  2, -7,  9]), array([ 1, -4,  5,  6]))

In [27]:
np.where((a > 2.5) | (a < 0), 1000/a, a**3+4) # можно писать сложную логику

array([   5.        ,   12.        , -142.85714286,  111.11111111])

# save to file

In [39]:
a = np.array([1, 2, -7, 9])
b = np.array([1, -4, 5, 6])
a, b

(array([ 1,  2, -7,  9]), array([ 1, -4,  5,  6]))

In [40]:
a = np.where(a <= 2, 0, a)

In [41]:
c = (a + b) / 7
c

array([ 0.14285714, -0.57142857,  0.71428571,  2.14285714])

In [42]:
saved = np.where((a > 2.5) | (b < 0), 1000/a, c)
saved

/tmp/ipykernel_26666/1765634283.py:1: RuntimeWarning: divide by zero encountered in divide
  saved = np.where((a > 2.5) | (b < 0), 1000/a, c)


array([  0.14285714,          inf,   0.71428571, 111.11111111])

In [43]:
np.save('saved_array', saved) # сохраняем массив в файл

In [44]:
np.load('saved_array.npy') # загружаем массив из файла

array([  0.14285714,          inf,   0.71428571, 111.11111111])

In [45]:
np.savez('saved_arrays', saved, a, b) # сохраняем несколько массивов в один файл

In [46]:
np.load('saved_arrays.npz') # загружаем массив из файла

NpzFile 'saved_arrays.npz' with keys: arr_0, arr_1, arr_2

In [51]:
# загружаем конкретный массив из файла в массив. иногда они называются arr_0, arr_1 и т.д.а иногда они называются по имени массива как было в переменной
np.load('saved_arrays.npz')['arr_0'] 

array([  0.14285714,          inf,   0.71428571, 111.11111111])

In [52]:
np.savez('saved_arrays_with_names', saved = saved, a = a, b = b)

In [53]:
np.load('saved_arrays_with_names.npz')['saved'] # загружаем массив по имени

array([  0.14285714,          inf,   0.71428571, 111.11111111])

# tasks .

Замените все отрицательные значения в массиве arr на 0, a неотрицательные на 1.

Выведите данный массив с типом данных bool.

In [28]:
arr = np.random.randint(-10, 10, 16)
arr

array([  2,  -8,   5,   3,  -6,  -2,  -6,   4,  -2,   5,  -1,  -6,   9,
        -9, -10,  -1])

In [29]:
def solution(arr):

    arr = np.where(arr < 0, 0, 1)

    return arr.astype(bool)

arr = solution(arr)
arr

array([ True, False,  True,  True, False, False, False,  True, False,
        True, False, False,  True, False, False, False])

На вход программе подаётся массив произвольного размера. Замените все отрицательные значения на их модуль, а положительные на 0.

In [31]:
arr = np.random.randint(-10, 10, 16)
arr

array([-4, -9,  4, -9, -2, -1,  9,  1,  4, -2, -2, -1,  7,  5, -1,  5])

In [32]:
def solution(arr):
    arr = np.where(arr < 0, np.abs(arr), 0)

    return arr

arr = solution(arr)
arr

array([4, 9, 0, 9, 2, 1, 0, 0, 0, 2, 2, 1, 0, 0, 1, 0])

На вход подаются два массива.

Замените все отрицательные значения меньшие или равные значениям из второго массива в первом массиве на значения из второго массива. В противном случае, замените значение на меньшее из двух массивов.

In [33]:
arr1 = np.random.randint(-10, 10, 16)
arr2 = np.random.randint(-10, 10, 16)
arr1, arr2

(array([-6,  9,  6,  8, -5, -3,  1, -7,  5, -5, -9, -1, -5,  3,  4,  0]),
 array([-5, -9, -2, -8, -6, -1, -2, -1,  7,  6, -8, -2, -4,  9, -5, -9]))

In [37]:
def solution(arr1, arr2):
    return np.where((arr1 <= arr2) & (arr1 < 0), arr2, np.minimum(arr1, arr2))


arr = solution(arr1, arr2)
arr

array([-5, -9, -2, -8, -6, -1, -2, -1,  5,  6, -8, -2, -4,  3, -5, -9])