In [2]:
import numpy as np

In [3]:
arr = np.array([1, 2, 3, 4, 5])

np.min(arr)

1

In [4]:
arr = np.arange(8).reshape(2, 4)
arr

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [5]:
arr[:,1]

array([1, 5])

Подается массив.

Найдите сумму положительных элементов массива.

In [6]:
arr = np.random.randint(-10, 10, 10)
arr

array([-2, -7,  3,  8,  1, -9,  2, -1,  1, -6])

In [7]:
def solution(arr):
    m = arr > 0

    
    return arr[m].sum()

arr = solution(arr)
arr

15

Подается массив (4, 4).

Верните массив максимальных значений по столбцам.

In [8]:
arr = np.random.randint(0, 10, 16).reshape(4, 4)
arr

array([[8, 3, 4, 8],
       [9, 3, 3, 8],
       [9, 7, 0, 6],
       [2, 6, 1, 6]])

In [9]:
# Верните массив максимальных значений по столбцам.
def solution(arr):
    return arr.max(axis=0)

arr = solution(arr)
arr

array([9, 7, 4, 8])

Подается два массива (4, 4).

Отсортируйте их по строкам и произведите сравнение (==). Верните получившуюся маску.

In [10]:
arr1 = np.random.randint(0, 4, 16).reshape(4, 4)
arr2 = np.random.randint(0, 4, 16).reshape(4, 4)
arr1, arr2

(array([[0, 0, 2, 0],
        [2, 1, 1, 3],
        [1, 3, 0, 1],
        [0, 1, 0, 1]]),
 array([[2, 3, 1, 1],
        [2, 1, 0, 2],
        [2, 3, 3, 2],
        [3, 1, 2, 0]]))

In [11]:
def solution(arr1, arr2):
    arr1.sort(axis=1)
    arr2.sort(axis=1)
    return arr1 == arr2

arr = solution(arr1, arr2)
arr

array([[False, False, False, False],
       [False,  True,  True, False],
       [False, False, False,  True],
       [ True, False, False, False]])

Подается матрица формы (4, 4). Если порядковое место наименьшего элемента больше порядкового места наибольшего, выведите среднее значение матрицы. В противном случае, выведите медиану.

In [22]:

arr = np.random.randint(0, 44, 16).reshape(4, 4)
arr, np.argmin(arr), np.argmax(arr), np.mean(arr), np.median(arr)

(array([[ 2, 13,  9,  2],
        [14, 38, 15, 14],
        [19,  0, 26, 33],
        [12, 41, 31,  8]]),
 9,
 13,
 17.3125,
 14.0)

In [20]:
def solution(arr):
    if np.argmin(arr) > np.argmax(arr):
        return np.mean(arr)
    else:
        return np.median(arr)
    

13

Подается 2 массива. Создайте массив из больших значений искомых массивов, после чего замените все отрицательные значения в получившемся массиве на их модуль. Выведите модуль разницы между средним значением получившегося массива и его медианой.

In [25]:
m1 = np.random.randint(-20, 20, 10)
m2 = np.random.randint(-20, 20, 10)
m1, m2

(array([ 15, -18,   6, -14, -10,  -9,   0, -15,  10,  -9]),
 array([-19, -18,  14,  14, -14,  13,  14,  12,  19,  -1]))

In [28]:
res = np.maximum(m1, m2)
res, np.abs(res)

(array([ 15, -18,  14,  14, -10,  13,  14,  12,  19,  -1]),
 array([15, 18, 14, 14, 10, 13, 14, 12, 19,  1]))

In [29]:
def solution(m1, m2):
    new_arr = np.maximum(m1, m2)
    new_arr = np.abs(new_arr)
    return np.abs(np.mean(new_arr) - np.median(new_arr))

arr = solution(m1, m2)
arr


1.0

Подается массив (4, 4).

Отсортируйте его по столбцам и выведите первые три элемента второй строки.

In [48]:
arr = np.random.randint(0, 10, 16).reshape(4, 4)
arr

array([[3, 4, 0, 1],
       [1, 8, 1, 9],
       [3, 0, 0, 3],
       [5, 2, 8, 8]])

In [49]:
arr.sort(axis=0) # Сортируем по столбцам
arr

array([[1, 0, 0, 1],
       [3, 2, 0, 3],
       [3, 4, 1, 8],
       [5, 8, 8, 9]])

In [54]:
arr[:,1], arr[1, :3]

(array([0, 2, 4, 8]), array([3, 2, 0]))

In [55]:
def solution(arr):
    arr.sort(axis=0)
    return arr[1, :3]

arr = solution(arr)
arr

array([3, 2, 0])

Подается три одномерных массива одинаковой формы.

Верните массив такой, что.

Если на i-м месте первого массива 0, то в данном массиве i-й элемент второго массива, взятый по модулю. В противном случае, там произведение второго и третьего массивов.

In [58]:
m1, m2, m3 = np.random.randint(-10, 10, 5), np.random.randint(-10, 10, 5), np.random.randint(-10, 10, 5)
m1, m2, m3

(array([ -2,  -7, -10,   1,  -1]),
 array([ 9,  7, -2,  0,  9]),
 array([-2, -5,  6,  3, -4]))

In [59]:
def solution(arr1, arr2, arr3):
    # Если элемент arr1 равен 0, выбираем элемент из arr2 по модулю, иначе произведение arr2 и arr3
    arr = np.where(arr1 == 0, np.abs(arr2), arr2 * arr3)
    return arr

На вход подаются два массива одинаковой формы.

Верните количество совпадающих элементов у этих массивов.

Если все их элементы совпадают, верните -1.

In [62]:
arr1 = np.random.randint(-2, 2, 15)
arr2 = np.random.randint(-2, 2, 15)

arr1, arr2

(array([ 1, -1, -1,  1, -2, -1,  1, -2, -1, -2,  1,  1,  0, -2, -1]),
 array([ 1,  0,  0, -1,  0, -2,  0, -2,  0,  0, -2, -2, -2, -2, -2]))

In [63]:
arr3 = np.where(arr1 == arr2, True, False)
arr3

array([ True, False, False, False, False, False, False,  True, False,
       False, False, False, False,  True, False])

In [65]:
np.all(arr3 == True)

False

In [66]:
def solution(arr1, arr2):
    arr3 = np.where(arr1 == arr2, True, False)
    if np.all(arr3 == True):
        return -1
    else:
        return np.count_nonzero(arr3)
    
print(solution(arr1, arr2))

3


На вход подается массив (4, 4). Посчитайте, какой элемент в данном массиве встречается чаще всего и верните его.




In [67]:
arr = np.random.randint(0, 10, 16).reshape(4, 4)
arr

array([[3, 6, 6, 0],
       [1, 8, 2, 6],
       [7, 7, 3, 8],
       [6, 2, 4, 5]])

In [68]:
# Получаем уникальные значения и их количество в двух массивах.
values, counts = np.unique(arr, return_counts=True) # Получаем уникальные значения и их количество



In [ ]:
def solution(arr):
    values, counts = np.unique(arr, return_counts=True)
    return values[np.argmax(counts)] # Возвращаем значение, которое встречается чаще всего

Со звездочкой

На вход подается произвольный массив.

Напишите программу, возвращающую его последний элемент (последний элемент последней строки последней матрицы и тп).

In [80]:
arr = np.arange(10)
arr2 = np.arange(16).reshape(4, 4)
arr3 = np.arange(36).reshape(3, 3, 4)  # Fix: Adjusted the number of elements to match the shape
arr, arr2, arr3


(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],
 
        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]],
 
        [[24, 25, 26, 27],
         [28, 29, 30, 31],
         [32, 33, 34, 35]]]))

In [84]:
arr3.flatten() # Преобразуем в одномерный массив

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [89]:
# ndim - количество измерений. tuple([-1] * arr.ndim) - возвращает кортеж с -1 для каждого измерения
tuple([-1] * arr.ndim), tuple([-1] * arr2.ndim), tuple([-1] * arr3.ndim)

((-1,), (-1, -1), (-1, -1, -1))

In [95]:
arr3.reshape(-1) # Преобразуем в одномерный массив

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [100]:
np.prod(arr3.shape)# Общее количество элементов в массиве

36