# 1D arrays
1. [create](#create)
2. [arithmetic operations](#arithmetic)
3. [types in arrays](#types)

In [4]:
import numpy as np

# create arrays
<a id="create"></a>

In [5]:
arr = np.array([1, 2, 3, 4, "5"])
arr

array(['1', '2', '3', '4', '5'], dtype='<U21')

In [6]:
arr = np.array([1, 2, 3, 4, 5.1])
arr

array([1. , 2. , 3. , 4. , 5.1])

In [7]:
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [8]:
arr1 = np.ones(5)
arr1

array([1., 1., 1., 1., 1.])

In [9]:
np0 = np.zeros(5)
np0

array([0., 0., 0., 0., 0.])

In [10]:
np.full(5, "uhuhuhu")

array(['uhuhuhu', 'uhuhuhu', 'uhuhuhu', 'uhuhuhu', 'uhuhuhu'], dtype='<U7')

In [11]:
import numpy as np

def solution():
    """
    Эта функция создает массив чисел от 0 до 99 с шагом 11.

    Args:
        None

    Returns:
        np.ndarray: Массив чисел от 0 до 99 с шагом 11.

    Raises:
        None
    """

    return np.arange(0, 100, 11)

print(solution())

[ 0 11 22 33 44 55 66 77 88 99]


In [12]:
import numpy as np

def solution(n):
    """
    This function returns an array of ones if the input is positive, and an array of zeros if the input is negative.

    Args:
        n (int): The input integer.

    Returns:
        np.ndarray: An array of ones if the input is positive, and an array of zeros if the input is negative.

    Raises:
        None
    """

    if n > 0:
        return np.ones(n)
    else:
        return np.zeros(abs(n))


# arithmetic operations
<a id="arithmetic"></a>

In [13]:
arr = np.arange(5)
arr 

array([0, 1, 2, 3, 4])

In [14]:
arr * 7

array([ 0,  7, 14, 21, 28])

In [15]:
arr - 7

array([-7, -6, -5, -4, -3])

In [16]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([5, 4, 3, 2, 1])

arr1 * arr2

array([5, 8, 9, 8, 5])

массивы должны быть одного размера

In [17]:
arr3 = np.array([1, 2, 3, 4, 5, 6])
arr1 * arr3

ValueError: operands could not be broadcast together with shapes (5,) (6,) 

оперции между ними можно проводить если все элементы одного типа(или числовые или стрококвые)

In [20]:
arr4 = np.array([1, 2, 3, 4, "5"])
arr1 * arr4    

UFuncTypeError: ufunc 'multiply' did not contain a loop with signature matching types (dtype('int64'), dtype('<U21')) -> None

если делим на ноль, то получаем inf(бесконечность)

In [21]:
arr5 = np.array([1, 2, 3, 4, 0])
arr1 / arr5

/tmp/ipykernel_10134/3243614470.py:2: RuntimeWarning: divide by zero encountered in divide
  arr1 / arr5


array([ 1.,  1.,  1.,  1., inf])

### Напишите программу, которая принимает на вход массив размерности N и возвращает массив утроенных обратных элементов этого массива.

In [ ]:
import numpy as np

def solution(arr):
    """
    принимает на вход массив размерности N и возвращает массив утроенных обратных элементов этого массива.
    обратно число это 1/число
    """
    

    return (1 / arr) * 3

### Напишите программу, которая принимает на вход одномерный массив длины N, возводит все элементы получившегося массива в куб и вычитает из них длину массива.

In [27]:
import numpy as np

def solution(arr):
    arr = (arr ** 3) - len(arr)    
    return arr

0.2


###  Напишите программу, которая принимает на вход 2 массива одинаковой длины и возвращает новый массив, в котором i-й элемент равен среднему квадратичному i-х элементов из заданных массивов.

In [31]:
import numpy as np

def solution(arr1, arr2):
    lst1 = []
    their_lenght = len(arr1)    
    for i in range(their_lenght):
        number = np.sqrt((arr1[i]**2 + arr2[i]**2) / 2)
        lst1.append(number)
    return np.array(lst1)

solution(np.array([1, 2, 3]), np.array([4, 5, 6]))


array([2.5, 3.5, 4.5])

In [ ]:
import numpy as np

def solution(arr1, arr2):
    return ((arr1 ** 2 + arr2 ** 2) / 2) ** 0.5

# Типы данных в массивах
<a id='types'></a>

In [2]:
a = 1
print(type(a))

<class 'int'>


In [26]:
arr_s = np.array(["asdasdasdasdasdasd1", "2", "a"])
arr_s

array(['asdasdasdasdasdasd1', '2', 'a'], dtype='<U19')

In [20]:
arr_s.dtype

dtype('<U21')

In [22]:
arr_s = np.array(["3", 'asd', 'asdasd'])
arr_s

array(['3', 'asd', 'asdasd'], dtype='<U6')

In [35]:
arr = np.array(["1", "2", "3", "4"])
arr

array(['1', '2', '3', '4'], dtype='<U1')

In [36]:
arr = arr.astype(int)

In [32]:
arr.dtype

dtype('int64')

In [43]:
arr = arr.astype(np.float64)
arr

array([1., 2., 3., 4.])

In [44]:
arr = np.array(["1", "2", "3", "4"], dtype=np.float32)
arr

array([1., 2., 3., 4.], dtype=float32)

In [45]:
true_mask = np.ones(4, dtype=bool)
true_mask

array([ True,  True,  True,  True])

In [46]:
true_mask = np.zeros(4, dtype=bool)
true_mask

array([False, False, False, False])

In [47]:
lst = [1.1, 2.999, 3.5, 4]
lst

[1.1, 2.999, 3.5, 4]

In [48]:
np.array(lst, dtype=np.int32) #значения не округляются, а просто отбрасываются 

array([1, 2, 3, 4], dtype=int32)

### Умножьте все значения поданного массива на 3 и верните тот же массив с типом значений int.



In [ ]:
import numpy as np

def solution(arr):
    arr = arr * 3
    return arr.astype(int)