In [15]:
#импорт библиотек
import numpy as np

### 1. Среднее

Предположим, что в некоторой компании работает 20 сотрудников. Проанализируем **возврасты сотрудников**

In [16]:
ages=[18, 20,25, 24, 18, 19, 26, 28, 29, 30, 30, 32, 33, 34, 36, 36, 44, 45, 48, 57]

In [17]:
#проверим для каждого ли сотрудника есть возвраст. Для этого посчитаем кол-во элементов в списке
len(ages)

20

In [18]:
#Минимальный и максимальный возвраст
print(np.min(ages), np.max(ages))

18 57


In [19]:
#посмотрим глазами есть ли повторяющиеся возрасты. Отсортируем список по возврастанию для удобства
print(np.sort(ages)) 

[18 18 19 20 24 25 26 28 29 30 30 32 33 34 36 36 44 45 48 57]


In [20]:
#проверим есть сотрудники с одинаковым возврастом с помощью подсчета уникальных значений в списке
print(np.unique(ages))
print(len(np.unique(ages)))

[18 19 20 24 25 26 28 29 30 32 33 34 36 44 45 48 57]
17


**Статистика** - это числовая характеристика выборки, расчитанная на основе выборки. Другими словами это число, которое возвращает любая функция, примененная к выборке.

Максимальный возвраст, минимальный возвраст, длина выборки, кол-во уникальных возврастов - это различные статистики.

Простая и в то же время одна из самых популярных статистик, с помощью которой мы можем описать выборку возврастов сотрудников - это среднее.</br>
Мы сталкиваемся с этой статистикой очень часто. Примеров много:
- Среднее количество учеников в классе;
- Среднее время, затрачиваемое на дорогу до работы;
- Среднее количество каллорий, употребляемых в день;
- Среднее количество шагов, пройденных за один день;
- Средняя заработная плата в Канаде;
- Средняя продолжительность жизни в Японии.

Среднее вычисляется очень просто. Необходимо сложить все значения выборки и разделить на количество значений в выборки.

Формула среднего:</br>

### $ \bar{x} = \frac 1 {n}{\sum\limits_{i=1}^{n} x_i} $

где: <br/> 
$ \bar{x} $- среднее;<br/> 
$ x_i $ - элемент выборки;<br/> 
$ n $- количесво наблюдений; <br/>  
$ {\sum\limits_{i=1}^{n}} $ -сумма всех наблюдений от 1 до n.

In [21]:
#Расчитаем среднее

#Шаг 1. Складываем все значения в списке
summa = np.sum(ages)
print(summa)

632


In [22]:
#Шаг 2. Считаем количество значений(элементов) в списке
count = len(ages)
print(count)

20


In [23]:
#Шаг 3. Делим сумму на количество
summa/count #получаем статистику "средний возраст в компании"

31.6

In [24]:
#В библиотеке numpy есть встроенная функция, с помощью которой можно посчитать среднее
np.mean(ages)

31.6

Теперь проанализируем **заработную плату** сотрудников.

In [25]:
salary = [50000, 50000, 80000, 80000, 120000, 120000, 130000, 150000, 140000, 190000, 80000, 150000, 250000, 600000, 150000, 100000, 210000, 150000, 600000, 2000000]

In [26]:
#Убедимся, что значений количество значений зарплат тоже 20
len(salary)

20

In [27]:
#Средняя зарплата в компании
np.mean(salary)

270000.0

Средняя зарплата в компании 270 000 рублей. Будем считать что это гораздо выше рынка. Давайте детальнее посмотрим на все зарплаты.

In [28]:
np.sort(salary)

array([  50000,   50000,   80000,   80000,   80000,  100000,  120000,
        120000,  130000,  140000,  150000,  150000,  150000,  150000,
        190000,  210000,  250000,  600000,  600000, 2000000])

In [29]:
#37% от всего бюджета на зарплаты - это зарплата генерального директора
np.max(salary)/np.sum(salary)*100

37.03703703703704

In [30]:
#59% от всего бюджета зарплат получает генеральный директор плюс 2 топ-менеджера
(600000+600000+2000000)/np.sum(salary)*100

59.25925925925925

Значения, которые аномально отличаются от большинства значений в выборке в большую или меньшую сторону, называются **выбросами**. Что значит "аномально" мы разберем позднее, а пока что приведу несколько примеров выбросов:
- Состояние Илона Маска среди всех состояний людей;
- Чек в супермаркете Пятерочка на 100 000 рублей при среднем чеке 500 рублей;
- Количество подписчиков в инстаграме у Криштиану Роналду среди всех аккаунтов.

### 2. Медиана

Среднее не очень точно отразило ситуацию с заработными платами сотрудников, потому что в выборке есть выбросы. 
Когда есть выбросы, на помощь приходит медиана.

In [31]:
#Еще раз посчитаем среднее
np.mean(salary)

270000.0

In [32]:
#Посчитаем медиану
np.median(salary)

145000.0

**Медиана** - это наблюдение (значение зарплаты), которое находится посереднине отсортированного набора данных.

In [33]:
#Расчитаем значение медианы вручную.

#Шаг 1: сортируем значения (обычно по возрастанию)
np.sort(salary)

array([  50000,   50000,   80000,   80000,   80000,  100000,  120000,
        120000,  130000,  140000,  150000,  150000,  150000,  150000,
        190000,  210000,  250000,  600000,  600000, 2000000])

In [34]:
#Шаг 2: находим значение посередине
#Так как у нас четное количество значений, мы берем два серединных значения
#cкадываем их и делим на 2
(140000+150000)/2

145000.0

In [35]:
#если количество значение нечетное, тогда немного проще. Сначала сортируем значения, а значение посередине - это медиана.
salary_fake= [  50000,   50000,   80000,   80000,   80000,  100000,  120000,
        120000,  130000,  140000,  145000, 150000,  150000,  150000,  150000,
        190000,  210000,  250000,  600000,  600000, 2000000]

In [36]:
len(salary_fake)

21

In [37]:
np.median(salary_fake)

145000.0

In [38]:
np.sort(salary_fake)

array([  50000,   50000,   80000,   80000,   80000,  100000,  120000,
        120000,  130000,  140000,  145000,  150000,  150000,  150000,
        150000,  190000,  210000,  250000,  600000,  600000, 2000000])

In [39]:
#10-й индекс в списке - это 11-е значение, в списке индексация начинается с нуля
np.sort(salary_fake)[10]

145000